version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      DEBUG: "1"
      PYTHONUNBUFFERED: "1"
    command: >
      sh -c "uv run manage.py migrate &&
             uvicorn selfory.asgi:application --host 0.0.0.0 --port 8000 --reload"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DEBUG: "1"
      PYTHONUNBUFFERED: "1"
    command: uv run celery -A selfory worker --loglevel=info

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DEBUG: "1"
      PYTHONUNBUFFERED: "1"
    command: uv run celery -A selfory beat --loglevel=info
