[project]
name = "selfory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-phonenumber-field>=8.1.0",
    "djangorestframework>=3.16.1",
    "phonenumbers>=9.0.14",
    "pillow>=11.3.0",
]
